version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: saturday
    allow:
      - dependency-type: production
      
  - package-ecosystem: *
    directory: /
    schedule:
      interval: monthly
      day: saturday
    allow:
      - dependency-type: development
