version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: saturday

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      day: saturday
    ignore:
      - dependency-name: "@actions/core"
        update-types: [ "version-update:semver-patch" ]

      - dependency-name: "@vercel/ncc"
        update-types: [ "version-update:semver-patch" ]

      - dependency-name: "eslint"
        update-types: [ "version-update:semver-minor", "version-update:semver-patch" ]

      - dependency-name: "jest"
        update-types: [ "version-update:semver-minor", "version-update:semver-patch" ]
