name: 'Send message to MS Teams (webhook)'
description: 'Send message to a channel in MS Teams using webhook'

inputs:
  webhookUrl:
    description: 'Incoming webhook URL'
    required: true
  message:
    description: 'Message to be sent to Teams'
    required: true

# Optional inputs
  title:
    description: 'Title of the message card'
    required: false
  status:
    description: 'Status of the Github job or step'
    required: false

# For environment variables see - https://github.com/neonidian/teams-notify-build-status#environment-variables

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'send'
  color: 'purple'
