name: 'Send message to MS Teams'
description: 'Post build status to MS Teams using a webhook'

inputs:
  webhookUrl:
    description: 'Incoming webhook URL'
    required: true
  message:
    description: 'Message to be sent to Teams'
    required: true

# Optional inputs
  jobStatus:
    description: 'Status of the Github job'
    required: false
    default: ${{ job.status }}
  githubToken:
    description: 'Github token'
    required: false

# For environment variables see https://github.com/neonidian/teams-notify-build-status#readme

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'send'
  color: 'purple'
