name: 'Post message to MS'
description: 'Post a message to MS Teams using a webhook URL'
inputs:
  webhookUrl:
    description: 'Incoming webhook URL'
    required: true
  message:
    description: 'Message to be sent'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
