name: 'Post message to MS'
description: 'Post build status to MS Teams using a webhook'
inputs:
  webhookUrl:
    description: 'Incoming webhook URL'
    required: true
  message:
    description: 'Message to be sent'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'send'
  color: 'purple'
