name: Update major version

on:
  release:
    types: [ published ]

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Install deps and build
        run: npm ci && npm run prepare

      - name: Update major version
        uses: JasonEtco/build-and-tag-action@5220ac2e69814ad86f9139a33d4f2de17c2272ea
        env:
          GITHUB_TOKEN: ${{ github.token }}
