name: Update major version

on:
  release:
    types: [ published ]

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Install deps and build
        run: npm ci && npm run prepare

      - name: Update major version
        uses: JasonEtco/build-and-tag-action@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
