name: "Quality"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  unit-and-system-tests:
    name: Run unit and systemt tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      # Requires TEAMS_TEST_HOOK_URL to be set as secrets
      - name: Run HTTP request tests
        run: npm run verify

  # test action works running from the graph
  test:
    name: Test action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: npm run prepare

      - uses: ./
        with:
          milliseconds: 1000
